"""Stable defaults and process exit codes for the AI-callable YMODEM CLI."""


DEFAULT_BAUDRATE = 115200
DEFAULT_TIMEOUT_SECONDS = 1.0
DEFAULT_MAX_RETRIES = 5
DEFAULT_FILE_MODE = 0o100644
DEFAULT_SERIAL_NUMBER = 0
DEFAULT_PORT_VID = None
DEFAULT_PORT_PID = None
DEFAULT_PORT_MATCHES = ()

BLOCK0_DATA_SIZE = 128
DATA_PACKET_SIZE = 1024
PADDING_BYTE = 0x1A
MAX_UINT32 = 0xFFFFFFFF

EXIT_SUCCESS = 0
EXIT_INVALID_ARGUMENT = 1
EXIT_PORT_NOT_FOUND = 2
EXIT_SERIAL_OPEN_FAILED = 3
EXIT_RECEIVER_TIMEOUT = 4
EXIT_TRANSFER_FAILED = 5
EXIT_RECEIVER_CANCELLED = 6
